project:
  type: book
  output-dir: docs

book:
  title: "Bayesian censoring"
  author: "handelgroup"
  date: last-modified
  date-format: iso
  chapters:
    - index.qmd
    - intro.qmd
    - ex1-simple-censored-outcome/index.qmd
    - ex2-simple-censored-predictor/index.qmd
    - ex3-censored-outcome-and-predictor/index.qmd
    - ex4-infection-outcome-with-censored-predictor/index.qmd
    - ex5-interval-censoring/index.qmd
    - ex6-HAI-data-outcome/index.qmd
    - references.qmd

bibliography: references.bib

execute:
  freeze: auto

filters:
  - include-code-files

format:
  html:
    theme: pulse



