project:
  type: book
  output-dir: docs

book:
  title: "Bayesian censoring"
  author: "handelgroup"
  date: last-modified
  date-format: iso
  chapters:
    - index.qmd
    - front-end/intro.qmd
    - part: "First models"
      chapters:
        - examples/simple-censored-outcome/index.qmd
        - examples/simple-censored-predictor/index.qmd
        - examples/censored-outcome-and-predictor/index.qmd
        - examples/censored-outcome-and-multiple-predictors/index.qmd
    - part: "Case studies"
      chapters: 
        - examples/nov-data-example/index.qmd
        - examples/interval-censoring-weibull/index.qmd
        - examples/HAI-data-example/index.qmd
    - part: "Implementation"
      chapters:
        - implementation/maximum-likelihood/index.qmd
        - implementation/brms/index.qmd
        - implementation/stan/index.qmd
    - front-end/references.qmd

bibliography: references.bib

execute:
  freeze: auto

filters:
  - include-code-files

format:
  html:
    theme: pulse



