project:
  type: book
  output-dir: docs

book:
  title: "Bayesian censoring"
  author: "handelgroup"
  date: last-modified
  date-format: iso
  chapters:
    - index.qmd
    - front-end/intro.qmd
    - examples/simple-censored-outcome/index.qmd
    - examples/simple-censored-predictor/index.qmd
    - examples/censored-outcome-and-predictor/index.qmd
    - examples/nov-data-example/index.qmd
    - examples/interval-censoring-weibull/index.qmd
    - examples/HAI-data-example/index.qmd
    - front-end/references.qmd

bibliography: references.bib

execute:
  freeze: auto

filters:
  - include-code-files

format:
  html:
    theme: pulse



