# What are censored data?

Censoring is a selection phenomenon on data which occurs when we can only
obtain precise measurements for certain measurement values. The classical
example is a scale which can only measure weights up to a certain threshold,
say $y_{\mathrm{max}}$. A scale that can measure any weight would produce the
set of measurements $\{y_1^*, y_2^*, \ldots, y_n^*\}$ where $n$ is the sample
size. We call these the **latent values** or **true values**. Our imperfect
scale would then produce the **observed values**,
$$
y_i = \begin{cases}
y_i^*, & y_i^* \leq y_{\mathrm{max}} \\
y_{\mathrm{max}}, & y_i^* > y_{\mathrm{max}}
\end{cases}; \quad i = 1, \ldots, n.
$$
Specifically, this is an example of **right censoring**, where there is an
**upper limit of detection**, or maximum value that we can observe with
precision.

We can also have the opposite case, where we can detect any theoretical
measurement above a certain value. In this case, the data are said to have a
**lower limit of detection** and this phenomenon is called **left censoring**.
For example, imagine we are testing the concentration of lead in the tap water
of several buildings. Our test cannot detect lead levels below 5 parts per
billion (ppb), but can detect any larger amount of lead. In that case, our
observed values would instead look like this:
$$
y_i = \begin{cases}
y_i^*, & y_i^* \geq y_{\mathrm{min}} \\
y_{\mathrm{min}}, & y_i^* < y_{\mathrm{min}}
\end{cases}; \quad i = 1, \ldots, n,
$$
where $y_{\mathrm{min}}$ is the lower limit of detection.

$$
y_i = \begin{cases}
y_i^*, & y_i^* \geq y_{\mathrm{min}} \\
y_{\mathrm{min}}, & y_i^* < y_{\mathrm{min}}
\end{cases}; \quad i = 1, \ldots, n,
$$

Finally, we can have interval censoring, where we know a data value is within
some interval, but we do not know precisely where the value lies within that
interval. An example of this is antibody titer dilutions: for flu HAI titer,
the values are typically reported as 10, 20, 40, etc., but a value of 10 does
not mean the precise value of the measurement should be 10, it means the true
value is between 10 and 20. If we assume our titer is measured on the log
scale and has no limits of detection, we could write
$$
y_i = \lfloor y_i^* \rfloor; \quad i = 1, \ldots, n,
$$
because we only perform a discrete number of dilutions. This gives us the
interval value for $y_i$ as
$$y_i \in \left[\lfloor y_i^* \rfloor, \lfloor y_i^* + 1 \rfloor\right).$$

A given variable can be subject to all of these types of censoring simultaneously:
for example, HAI titers are interval censored in this way, but they also have
lower limits of detection and upper limits of detection as well (though the
upper limits are rarely important in practice because they can be arbitrarily
increased during the assay). However, a particular observation of this variable
can only be subject to one type of censoring at a time: e.g., if an observation
is below the detection limit, that value is left censored, it cannot simultaneously
be right censored or interval censored.

Notably, the distinction between "types" of censoring in this way is useful for
several analytic methods, but is not strictly necessary. All censored values can
be implicitly treated as interval censored data, where the lower endpoint for
a left censored value is negative infinity, and the upper endpoint for a
right censored value is positive infinity. Thus, we could write the data
generating process for HAI titers with LOD as
$$
y_i = \begin{cases}
y_{\text{min}}, \ y_i^* < y_{\text{min}}\\
\lfloor y_i^* \rfloor, \ y_{\text{min}} \leq y_i^* < y_{\text{max}} \\
y_{\text{max}}, y \leq y_{\text{max}}
\end{cases},
$$
where $y_{\text{min}}$ is the lower limit of detection and $y_{\text{max}}$
is the upper limit of detection. To express the DGP in interval
notation, we would write
$$
y_i \in \begin{cases}
\left(-\infty, y_{\text{min}}\right), \ y_i^* < y_{\text{min}}\\
\left[\lfloor y_i^* \rfloor, \lfloor y_i^* + 1 \rfloor\right), \ y_{\text{min}} \leq y_i^* < y_{\text{max}} \\
\left[y_{\text{max}}, \infty\right), \ y \leq y_{\text{max}}
\end{cases}.
$$
Note also that assuming $y^*_i$ is drawn from an absolutely continuous distribution
(e.g. normal or lognormal, etc.), the final likelihood model will be equivalent
regardless of which intervals are open or closed. This model would allow
us to put all of the censored observations into the likelihood function in the same
framework without having to worry about sorting the observations into buckets
w.r.t. the type of censoring.

The probability of each observation $y_i$ can then be expressed as the
probability that the random variable $Y$ takes on a realization inside the
given interval. If $F$ is the CDF for some parametric distribution which we
assume the latent variable $y_i^*$ is drawn from, with parameter $\theta$,
the contribution of $y_i$ to the likelihood is then
$$\mathcal{L}(\theta \mid Y_i) = F(\text{upper limit of interval}) - F(\text{lower limit of interval}).$$
If we call the lower limit of the interval for $y_i$ $L_i$ and the corresponding
upper limit $U_i$, we can write the likelihood of the sample as
$$
\mathcal{L}(\theta \mid \mathbf{Y}) = \prod_{i=1}^n \left(
F(y_i \mid \theta)\bigg\rvert_{y_i = L_i}^{U_i}
\right)^{C_i}\bigg(f(y_i\mid \theta) \bigg)^{C_i},
$$
where $C_i$ is the indicator variable for $y_i$ being censored. Notably, for an uncensored observation the likelihood is equal to the density. However, for the typical
types of HAI data that we see, all of the assay values are subject to the
same censoring process, and thus we could neglect the density component.

So now the remaining issue is to specify $F$, the CDF of the latent variables.

<!-- END OF FILE -->
